# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Node.js LTS Alpine base image
FROM node:lts-alpine

# Create application directory
WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the project into dist/
RUN npm run build

# Default command: start the MCP server via stdio
CMD ["node", "dist/server.js"]
